###
GET http://localhost:5000/api/user/abc

###
GET http://localhost:5000/api/user/random

###
GET http://localhost:5000/api/user/all

###
GET http://localhost:5000/api/user/all?limit=3

###
POST http://localhost:5000/api/user/save

###
DELETE http://localhost:5000/api/user/delete/9

###
PATCH http://localhost:5000/api/user/update/9

###
PATCH http://localhost:5000/api/user/bulk-update


